### ISSUE TITLE
CE in Artikelübersicht verursacht Query-Error durch FIND_IN_SET()

### ISSUE THREAD

**Issue by mariaj** [timgatzky/pct_customelements_attribute_tags#52]
CE verursacht durch Tag-Attribut mit ausgefüllter SQL-Bedingung einen Query-Error. 
FIND_IN_SET(id, 'xx') wird ohne Prüfung auf vorhandene Bedingung und somit ohne AND angehängt.

**Comment by timgatzky** [comment]
added AND in: b4abf821460c2cebd4c74c1a564656dc0cdec004
