### ISSUE TITLE
Optional value field in tl_pct_customelement_tags or filter value shows ids instead of readable values

### ISSUE THREAD

**Issue by timgatzky** [timgatzky/pct_customelements_attribute_tags#68]
Optionales Wertefeld oder die IDs als reine Werte im Filter (GET) nutzen, spart das zusätzliche DB Feld und ist sehr performant, weil direkte Abfrage möglich und nicht Wertesuche

**Comment by timgatzky** [comment]
Oder die IDs als reine Werte nutzen, spart ein DB Feld

**Comment by eBlick** [comment]
ID reicht, Hauptsache es sind Sonderzeichen/Leerzeichen möglich.
